In [0]:
data = spark.sql('SELECT * from linkedin')
data = data.toPandas()
data.head()

Post_ID 
 Text 
 
 
 
 
 0 
 1 
 Normalization is a technique often applied as ... 
 
 
 1 
 2 
 Training a Machine Learning Model in PyCaret e... 
 
 
 2 
 3 
 If an AI algorithm turns the copyrighted work ... 
 
 
 3 
 4 
 Do you know you can write nested functions in ... 
 
 
 4 
 5 
 Have you still not used PyCaret? Maybe it's ti...

In [0]:
print(data['Text'][0])

Normalization is a technique often applied as part of data preparation before training machine learning models. The goal of normalization is to rescale the values of numeric features in the dataset without distorting differences in the ranges of values or losing information.

This can be achieved in PyCaret using the normalize parameter within the setup. There are several methods available for normalization, by default it uses ‘zscore’ to normalize the data, which can be changed using the normalize_method parameter within setup.


In [0]:
print(data['Text'][1])

Training a Machine Learning Model in PyCaret extremely simple and can be done by using the create_model function. It takes only one parameter i.e. the Model ID as a string.

For supervised modules (classification and regression) this function returns a table with k-fold cross-validated performance metrics along with the trained model object.

For the unsupervised clustering module, it returns performance metrics along with the trained model object, and for anomaly detection, natural language processing, and association rule mining modules, it only returns the trained model object.

The number of folds can be defined using the 'fold' parameter (by default it uses 10 folds). To just train a model without the need for any performance evaluation you can set the 'cross_validation' to False.

See example code below


# Text Preprocessing

- Convert text into tokens
- Remove stop words
- Stem / Lemmatize
- Build bag of words

The only thing different this time is, instead of working with one text we have 10 text (in NLP terminology: we have 10 documents).

In [0]:
text = list(data['Text'])

In [0]:
type(text)

Out[5]: list

In [0]:
len(text)

Out[6]: 10

In [0]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-dat

In [0]:
import re
from nltk.corpus import stopwords

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

corpus = []

for i in range(len(text)):
    r = re.sub('[^a-zA-Z]', ' ', text[i])
    r = r.lower()
    r = r.split()
    r = [word for word in r if word not in stopwords.words('english')]
    r = [lemmatizer.lemmatize(word) for word in r]
    r = ' '.join(r)
    corpus.append(r)

In [0]:
type(corpus)

Out[9]: list

In [0]:
len(corpus)

Out[10]: 10

In [0]:
print(text[0])

Normalization is a technique often applied as part of data preparation before training machine learning models. The goal of normalization is to rescale the values of numeric features in the dataset without distorting differences in the ranges of values or losing information.

This can be achieved in PyCaret using the normalize parameter within the setup. There are several methods available for normalization, by default it uses ‘zscore’ to normalize the data, which can be changed using the normalize_method parameter within setup.


In [0]:
print(corpus[0])

normalization technique often applied part data preparation training machine learning model goal normalization rescale value numeric feature dataset without distorting difference range value losing information achieved pycaret using normalize parameter within setup several method available normalization default us zscore normalize data changed using normalize method parameter within setup


# Bag of Words (CountVectorizer)
The bag-of-words model is a simplifying representation used in natural language processing and information retrieval (IR). In this model, a text (such as a sentence or a document) is represented as the bag (multiset) of its words, disregarding grammar and even word order but keeping multiplicity. The bag-of-words model has also been used for computer vision.

The bag-of-words model is commonly used in methods of document classification where the (frequency of) occurrence of each word is used as a feature for training a classifier.

An early reference to "bag of words" in a linguistic context can be found in Zellig Harris's 1954 article on Distributional Structure. (Wikipedia)

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [0]:
# fit transform the CountVectorizer
X = cv.fit_transform(corpus)

In [0]:
# check the type of X
type(X)

Out[15]: scipy.sparse.csr.csr_matrix

In [0]:
# what is stored in X
print(X)

  (0, 192)	3
  (0, 303)	1
  (0, 198)	1
  (0, 13)	1
  (0, 210)	1
  (0, 61)	2
  (0, 225)	1
  (0, 312)	1
  (0, 165)	1
  (0, 155)	1
  (0, 181)	1
  (0, 121)	1
  (0, 250)	1
  (0, 332)	2
  (0, 195)	1
  (0, 108)	1
  (0, 62)	1
  (0, 339)	1
  (0, 75)	1
  (0, 73)	1
  (0, 238)	1
  (0, 161)	1
  (0, 142)	1
  (0, 0)	1
  (0, 234)	1
  :	:
  (9, 293)	1
  (9, 111)	1
  (9, 8)	2
  (9, 154)	1
  (9, 48)	1
  (9, 270)	5
  (9, 14)	1
  (9, 280)	2
  (9, 148)	5
  (9, 150)	3
  (9, 323)	2
  (9, 104)	1
  (9, 49)	1
  (9, 12)	1
  (9, 306)	4
  (9, 76)	4
  (9, 42)	1
  (9, 321)	1
  (9, 278)	1
  (9, 131)	1
  (9, 342)	1
  (9, 187)	1
  (9, 135)	1
  (9, 3)	1
  (9, 43)	1


In [0]:
# convert X to array
X_array = X.toarray()

In [0]:
# check type of X_array
type(X_array)

Out[18]: numpy.ndarray

In [0]:
# shape of X_array
X_array.shape

Out[19]: (10, 346)

In [0]:
print(X_array)

[[1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 1 0]
 [0 0 1 ... 0 0 0]]


In [0]:
# convert X_array into pandas dataframe
import pandas as pd
df = pd.DataFrame(X_array)
df

0 
 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9 
 10 
 11 
 12 
 13 
 14 
 15 
 16 
 17 
 18 
 19 
 20 
 21 
 22 
 23 
 24 
 25 
 26 
 27 
 28 
 29 
 30 
 31 
 32 
 33 
 34 
 35 
 36 
 37 
 38 
 39 
 ... 
 306 
 307 
 308 
 309 
 310 
 311 
 312 
 313 
 314 
 315 
 316 
 317 
 318 
 319 
 320 
 321 
 322 
 323 
 324 
 325 
 326 
 327 
 328 
 329 
 330 
 331 
 332 
 333 
 334 
 335 
 336 
 337 
 338 
 339 
 340 
 341 
 342 
 343 
 344 
 345 
 
 
 
 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 2 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 
 
 1 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 1 
 3 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 2 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 2 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 
 
 3 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 5 
 5 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 5 
 ... 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 1 
 5 
 7 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 
 
 4 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 2 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 5 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 ... 
 0 
 0 
 1 
 0 
 0 
 0 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 2 
 0 
 3 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 6 
 0 
 0 
 0 
 0 
 0 
 0 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 1 
 2 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 7 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 2 
 ... 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 
 
 8 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 1 
 2 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 2 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 9 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 4 
 0 
 0 
 0 
 0 
 0 
 4 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 2 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 
 
 
 10 rows × 346 columns

In [0]:
# assign column names to df
df.columns = cv.get_feature_names()
df.head(10)

achieved 
 ai 
 algorithm 
 allows 
 along 
 also 
 alteryx 
 among 
 amount 
 analyze 
 anomaly 
 api 
 application 
 applied 
 approach 
 arima 
 association 
 automl 
 available 
 average 
 averaged 
 away 
 back 
 base 
 basically 
 best 
 better 
 boilerplate 
 broadly 
 built 
 bunch 
 called 
 case 
 catboost 
 categorized 
 category 
 certain 
 changed 
 choice 
 choose 
 ... 
 text 
 thats 
 time 
 tool 
 train 
 trained 
 training 
 transformation 
 tree 
 true 
 tune 
 tuned 
 turn 
 tutorial 
 two 
 type 
 understand 
 unlabeled 
 unsupervised 
 us 
 use 
 used 
 using 
 usually 
 validated 
 validation 
 value 
 variable 
 version 
 want 
 way 
 whats 
 within 
 without 
 work 
 workload 
 would 
 write 
 xgboost 
 zscore 
 
 
 
 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 2 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 
 
 1 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 1 
 3 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 2 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 2 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 
 
 3 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 5 
 5 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 5 
 ... 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 1 
 5 
 7 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 
 
 4 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 2 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 5 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 ... 
 0 
 0 
 1 
 0 
 0 
 0 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 2 
 0 
 3 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 6 
 0 
 0 
 0 
 0 
 0 
 0 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 1 
 2 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 7 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 2 
 ... 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 
 
 8 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 1 
 2 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 2 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 9 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 4 
 0 
 0 
 0 
 0 
 0 
 4 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 2

In [0]:
# You can now concat these features in the original data
new_data = pd.concat([data,df], axis=1)
new_data

Post_ID 
 Text 
 achieved 
 ai 
 algorithm 
 allows 
 along 
 also 
 alteryx 
 among 
 amount 
 analyze 
 anomaly 
 api 
 application 
 applied 
 approach 
 arima 
 association 
 automl 
 available 
 average 
 averaged 
 away 
 back 
 base 
 basically 
 best 
 better 
 boilerplate 
 broadly 
 built 
 bunch 
 called 
 case 
 catboost 
 categorized 
 category 
 certain 
 changed 
 ... 
 text 
 thats 
 time 
 tool 
 train 
 trained 
 training 
 transformation 
 tree 
 true 
 tune 
 tuned 
 turn 
 tutorial 
 two 
 type 
 understand 
 unlabeled 
 unsupervised 
 us 
 use 
 used 
 using 
 usually 
 validated 
 validation 
 value 
 variable 
 version 
 want 
 way 
 whats 
 within 
 without 
 work 
 workload 
 would 
 write 
 xgboost 
 zscore 
 
 
 
 
 0 
 1 
 Normalization is a technique often applied as ... 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 ... 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 2 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 
 
 1 
 2 
 Training a Machine Learning Model in PyCaret e... 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 1 
 3 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 2 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 2 
 3 
 If an AI algorithm turns the copyrighted work ... 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 
 
 3 
 4 
 Do you know you can write nested functions in ... 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 5 
 5 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 1 
 5 
 7 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 
 
 4 
 5 
 Have you still not used PyCaret? Maybe it's ti... 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 2 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 5 
 6 
 Comparing estimators at the base level perform... 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 ... 
 0 
 0 
 1 
 0 
 0 
 0 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 2 
 0 
 3 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 6 
 7 
 In this tutorial, I will show you how you can ... 
 0 
 0 
 0 
 0 
 0 
 0 
 3 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 0 
 0 
 1 
 2 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 2 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 7 
 8 
 I know both are desirable but If I have to cho... 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 ... 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 
 
 8 
 9 
 Time Series Forecasting with PyCaret Regressio... 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 2 
 0 

# TF-IDF
In information retrieval, tf–idf, TF*IDF, or TFIDF, short for term frequency–inverse document frequency, is a numerical statistic that is intended to reflect how important a word is to a document in a collection or corpus. It is often used as a weighting factor in searches of information retrieval, text mining, and user modeling. The tf–idf value increases proportionally to the number of times a word appears in the document and is offset by the number of documents in the corpus that contain the word, which helps to adjust for the fact that some words appear more frequently in general. tf–idf is one of the most popular term-weighting schemes today. A survey conducted in 2015 showed that 83% of text-based recommender systems in digital libraries use tf–idf.

Variations of the tf–idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query. tf–idf can be successfully used for stop-words filtering in various subject fields, including text summarization and classification. (Wikipedia)

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

# fit transform the TfidfVectorizer
X = tfidf.fit_transform(corpus)

# convert X to array
X_array = X.toarray()

df = pd.DataFrame(X_array)
df.columns = tfidf.get_feature_names()

new_data = pd.concat([data,df], axis=1)
new_data

Post_ID 
 Text 
 achieved 
 ai 
 algorithm 
 allows 
 along 
 also 
 alteryx 
 among 
 amount 
 analyze 
 anomaly 
 api 
 application 
 applied 
 approach 
 arima 
 association 
 automl 
 available 
 average 
 averaged 
 away 
 back 
 base 
 basically 
 best 
 better 
 boilerplate 
 broadly 
 built 
 bunch 
 called 
 case 
 catboost 
 categorized 
 category 
 certain 
 changed 
 ... 
 text 
 thats 
 time 
 tool 
 train 
 trained 
 training 
 transformation 
 tree 
 true 
 tune 
 tuned 
 turn 
 tutorial 
 two 
 type 
 understand 
 unlabeled 
 unsupervised 
 us 
 use 
 used 
 using 
 usually 
 validated 
 validation 
 value 
 variable 
 version 
 want 
 way 
 whats 
 within 
 without 
 work 
 workload 
 would 
 write 
 xgboost 
 zscore 
 
 
 
 
 0 
 1 
 Normalization is a technique often applied as ... 
 0.134066 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.134066 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.113969 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.134066 
 ... 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.088649 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.113969 
 0.000000 
 0.000000 
 0.143941 
 0.000000 
 0.000000 
 0.000000 
 0.199418 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.268133 
 0.088649 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.134066 
 
 
 1 
 2 
 Training a Machine Learning Model in PyCaret e... 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.195938 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.097969 
 0.000000 
 0.00000 
 0.000000 
 0.00000 
 0.000000 
 0.097969 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 ... 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.072863 
 0.218588 
 0.064780 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.083283 
 0.083283 
 0.000000 
 0.000000 
 0.105185 
 0.000000 
 0.097969 
 0.083283 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.064780 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 
 
 2 
 3 
 If an AI algorithm turns the copyrighted work ... 
 0.000000 
 0.251851 
 0.187309 
 0.00000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 ... 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.251851 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.251851 
 0.000000 
 0.000000 
 0.251851 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.000000 
 
 
 3 
 4 
 Do you know you can write nested functions in ... 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.048309 
 0.00000 
 0.048309 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.00000 
 0.000000 
 0.00000 
 0.000000 
 0.000000 
 0.048309 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.048309 
 0.205337 
 0.241547 
 0.000000 
 0.000000 
 0.000000 
 0.048309 
 0.000000 
 0.041067 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 0.000000 
 ... 
 0.0